### PR TITLE
orienting synthetics workflow on experiment

### PR DESCRIPTION
**Pull request by TimOliverMaier**
What this PR is about:

I am trying to design the construction of synthetic data similar to the experimental workflow in an OOP modular fashion.

### CODE REVIEW

**Comment by TimOliverMaier** [comment]
This should be considered a Draft. My Mistake. I can't change it unfortunately

**Comment by theGreatHerrLebert** [comment]
@TimOliverMaier should make sure that MzSpectra are sorted by mz values.

**Comment by theGreatHerrLebert** [comment]
rename NeuralMobilityApex -> NeuralIonMobilityApex.

**Comment by theGreatHerrLebert** [comment]
shift implementation from ccs_to_one_over_reduced_mobility to device class, since temperature and drift gas is a parameter of the function.

**Pull request merged**
